on: push
#  schedule:
#    - cron: "0 0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: push to TypeTalk
        env:
          MESSAGE: "- 50単語やる
          - 2時までに布団に入る
          - 運動する"
        run: |
          curl --data-urlencode 'message=$MESSAGE' -H 'X-TYPETALK-TOKEN: ${{ secrets.TYPETALK_TOKEN }}' https://typetalk.com/api/v1/topics/${{ secrets.TYPETALK_TOPIC_ID }}
